# Generated by Django 6.0.4 on 2026-04-20 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descrizione', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ordine', models.DateTimeField(auto_now_add=True)),
                ('stato', models.CharField(choices=[('in_attesa', 'In Attesa'), ('in_preparazione', 'In Preparazione'), ('completato', 'Completato'), ('annullato', 'Annullato')], default='in_attesa', max_length=20)),
                ('totale', models.FloatField(default=0.0)),
                ('note', models.TextField(blank=True, null=True)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordini', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ordine',
            },
        ),
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('prezzo', models.FloatField()),
                ('disponibile', models.IntegerField(default=1)),
                ('immagine_url', models.URLField(blank=True, max_length=500, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodotti', to='api.categoria')),
            ],
            options={
                'db_table': 'prodotto',
            },
        ),
        migrations.CreateModel(
            name='OrdineProdotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.PositiveIntegerField(default=1)),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ordine')),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.prodotto')),
            ],
            options={
                'db_table': 'ordine_prodotto',
            },
        ),
        migrations.AddField(
            model_name='ordine',
            name='prodotti',
            field=models.ManyToManyField(through='api.OrdineProdotto', to='api.prodotto'),
        ),
    ]
